name: flow_by_spooky_services
description: "Flow by Spooky Services"
publish_to: 'none'
version: 0.0.19+24

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  chat_bubbles: ^1.7.0
  dynamik_theme: ^0.1.4
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  flutter_phoenix: ^1.1.1
  url_launcher: ^6.3.2
  http: ^1.3.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  web: ^1.1.1
  fluttertoast: ^8.2.12
  flutter_linkify: ^6.0.0
  go_router: ^16.2.4
  spookyservices:
    path: /home/kipper/Documents/GitKraken/SpookyServices
  go_transitions: ^0.8.2
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/RacingTouch.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000" # or your background color
  adaptive_icon_foreground: "assets/icon/icon.png"