name: hkjc_updater
description: "Helps you update HKJC Apps easily!"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  spookyservices:
    path: /home/kipper/Documents/GitKraken/SpookyServices
  webview_flutter: ^4.13.0
  ota_update: ^6.0.0
  go_transitions: ^0.8.2
  dynamik_theme: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/RacingTouch.png
    - assets/images/hkjctv.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000" # or your background color
  adaptive_icon_foreground: "assets/images/logo.png"